import graphviz

# https://pypi.org/project/graphviz/

dot = graphviz.Digraph(engine="neato")
dot.attr(overlap='false')
dot.attr(splines='true')
dot.node('V1', 'Wizards hut', shape='box', fontsize='20', fillcolor='#ff0000', style='filled,rounded', color='#00FF00',
         fontcolor='#0000FF')
dot.node('V2', 'Elixir')
dot.node('V3', 'Wizard')
dot.node('V4', 'Dragon lair')
dot.node('V5', 'Dragon')
dot.node('V6', 'Forest')
dot.node('V7', 'Road')
dot.node('V8', 'Lawyer')
dot.node('V9', 'Letter')
dot.node('V10', 'Main hero')
dot.node('V11', 'Sword')
dot.node('V12', 'Goal')
dot.node('V13', 'Pasture')
dot.node('V14', 'Village')
dot.node('V15', 'Well')
dot.node('V16', 'Inn')
dot.node('V17', 'Table')
dot.node('V18', 'Chair')
dot.node('V19', 'Chest')
dot.node('V20', 'Map')
dot.node('V21', 'Innkeeper')
dot.node('V22', 'Poison')
dot.node('V23', 'Drunkard')
dot.node('V24', 'Alcohol')


dot.edge('V5', 'V4')
dot.edge('V4', 'V6')
dot.edge('V6', 'V7')
dot.edge('V7', 'V1')
dot.edge('V1', 'V2')
dot.edge('V1', 'V3')
dot.edge('V7', 'V8')
dot.edge('V8', 'V9')
dot.edge('V7', 'V10')
dot.edge('V10', 'V12')
dot.edge('V10', 'V11')
dot.edge('V7', 'V13')
dot.edge('V7', 'V14')
dot.edge('V13', 'V14')
dot.edge('V14', 'V15')
dot.edge('V16', 'V7')
dot.edge('V16', 'V17')
dot.edge('V16', 'V19')
dot.edge('V19', 'V20')
dot.edge('V16', 'V23')
dot.edge('V23', 'V24')
dot.edge('V16', 'V21')
dot.edge('V21', 'V22')
dot.edge('V16', 'V18')

dot.render('round-table', view=True)
